package fruiton.kernel.targetPatterns;

import fruiton.dataStructures.Vector2;
import fruiton.IAbstractClass;
import fruiton.kernel.exceptions.InvalidArgumentException;
import fruiton.kernel.exceptions.Exception;

typedef Targets = Array<Vector2>;

/**
 * Immutable abstract base class for target patterns
 */
class TargetPattern implements IAbstractClass implements IHashable {

    var vector:Vector2;
    var min:Int;
    var max:Int;

    function new (vector:Vector2, min:Int, max:Int) {
        this.vector = vector;
        this.min = min;
        this.max = max;
    }

    /**
     * Generates all targets from orgin by this target pattern
     * @param origin - relative to origin are targets generated
     * @return Targets generated by this target pattern from given origin
     */
    public function getTargets(origin:Vector2):Targets {
        if (origin == null) {
            throw new InvalidArgumentException("Origin cannot be null.");
        }
        return new Targets();
    }

    public function getHashCode():Int {
        throw new Exception("Generic target pattern class does not have hash function");
    }
}
