package fruiton.kernel.targetPatterns;

import fruiton.dataStructures.Vector2;

typedef Targets = Array<Vector2>;

/**
 * Immutable class representing target pattern
 */
class TargetPattern {

    var vector:Vector2;
    var min:Int;
    var max:Int;

    function new (vector:Vector2, min:Int, max:Int) {
        this.vector = vector;
        this.min = min;
        this.max = max;
    }

    /**
     * Generates all targets from orgin by this target pattern
     * @param origin - relative to origin are targets generated
     * @return Targets generated by this target pattern from given origin
     */
    public function getTargets(origin:Vector2):Targets {
        return new Targets();
    }
}
